"""add observacao to order_items

Revision ID: 65dc3f1f18c0
Revises: 9d0182fbb077
Create Date: 2026-03-22 15:43:01.568410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65dc3f1f18c0'
down_revision: Union[str, Sequence[str], None] = '9d0182fbb077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('observacao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'observacao')
    # ### end Alembic commands ###
