"""add tables and table fields

Revision ID: 7488fe2259bb
Revises: 65dc3f1f18c0
Create Date: 2026-03-22 16:11:52.208289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7488fe2259bb'
down_revision: Union[str, Sequence[str], None] = '65dc3f1f18c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('table_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'table_number')
    op.drop_column('orders', 'table_id')
    # ### end Alembic commands ###
