"""fix impresso column

Revision ID: 9d0182fbb077
Revises: b60f9bdc3d01
Create Date: 2026-03-22 12:37:30.790893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0182fbb077'
down_revision: Union[str, Sequence[str], None] = 'b60f9bdc3d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('impresso', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'impresso')
    # ### end Alembic commands ###
